const C='summerhouse-v117-test';
const F=['./','index.html','room1.jpg','kitchen-room2.jpg','outside.jpg','lake.jpg','garden.jpg','garden-set.jpg','garden-eve.jpg','garden-nt.jpg','garden-n2.jpg','sign-sil.png','sign-face.png','osign-sil.png','osign-face.png','outside-pm.jpg','outside-set.jpg','outside-eve.jpg','outside-tw.jpg','outside-nt.jpg','bath.jpg','bathtub.jpg','kitchen-sunset.jpg','kitchen-dusk.jpg','kitchen-midnight.jpg','kitchen-twilight.jpg','kitchen-night.jpg','room-afternoon.jpg','room-sunset.jpg','room-dusk.jpg','room-twilight.jpg','room-night.jpg','room-latenight.jpg','room-midnight.jpg','fan-night.png','fan-twilight.png','fan-room1.png','fan-pm.png','fan-sunset.png','fan-dusk.png','curtain-left.png','curtain-right.png','chiikawa.png','chiikawa-open.png','chiikawa-blink.png','chiikawa-blink-open.png','chiikawa-hurt1.png','chiikawa-hurt2.png','chiikawa-surprise-red.png','chiikawa-shy-a.png','chiikawa-shy-b.png','berry.woff','bgm-s.mp3','ambient-s.mp3','ambient-eve-s.mp3','fan-intro2-s.mp3','fan-loop2-s.mp3','fan-fo1-s.mp3','fan-fo2-s.mp3','fan-fo3-s.mp3','hurt-s.mp3','hit1-s.mp3','sing1-s.mp3','hsing-s.mp3','surprise-s.mp3','knock-s.mp3','knock-k.mp3','step-s.mp3','step-k.mp3','face-chiikawa.png','face-hachiware.png','hachiware-peek.png','usagi-peek.png','hachi-come-s.mp3','hachi-live-s.mp3','usagi-hint-s.mp3','usagi-arrive-s.mp3','hachiware-open.png','hachiware-blink.png','hachiware-blink-open.png','manifest.json','icon-192.png','icon-512.png'];
self.addEventListener('install',e=>{e.waitUntil(caches.open(C).then(c=>c.addAll(F)));self.skipWaiting()});
self.addEventListener('activate',e=>{e.waitUntil(caches.keys().then(k=>Promise.all(k.filter(n=>n!==C).map(n=>caches.delete(n)))));self.clients.claim()});
self.addEventListener('fetch',e=>{if(e.request.method!=='GET')return;
  // 아이폰은 오디오를 Range 요청으로 가져와서, 캐시에서도 206 응답으로 잘라서 줘야 해요
  if(e.request.headers.has('range')){e.respondWith(caches.match(e.request.url).then(r=>{if(!r)return fetch(e.request);return r.arrayBuffer().then(b=>{const m=/bytes=(\d+)-(\d*)/.exec(e.request.headers.get('range'))||[0,0,''];const s=+m[1],n=m[2]?Math.min(+m[2],b.byteLength-1):b.byteLength-1;return new Response(b.slice(s,n+1),{status:206,headers:{'Content-Type':r.headers.get('Content-Type')||'audio/mpeg','Content-Range':'bytes '+s+'-'+n+'/'+b.byteLength,'Content-Length':String(n-s+1)}})})}));return}
  // [성능] 그림·소리 같은 큰 파일은 캐시에 있으면 바로 쓰고(매번 다시 받아 덮어쓰지 않음), 페이지/스크립트만 최신본을 먼저 확인해요
  {const u=new URL(e.request.url),big=u.origin===location.origin&&/\.(png|jpe?g|mp3|woff2?)$/i.test(u.pathname);
   if(big){e.respondWith(caches.match(e.request).then(r=>r||fetch(e.request).then(res=>{if(res&&res.ok){const cp=res.clone();caches.open(C).then(c=>c.put(e.request,cp))}return res})));return}}
  e.respondWith(fetch(e.request).then(res=>{if(res&&res.ok&&new URL(e.request.url).origin===location.origin){const cp=res.clone();caches.open(C).then(c=>c.put(e.request,cp))}return res}).catch(()=>caches.match(e.request)))});
